config/routes.rb
Products::Application.routes.draw do

  resources :categories do
    resources :products do
      resources :reviews
    end
  end
  resources :products do
    resources :reviews
  end
  resources :categories

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout'}

  root to: 'products#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products, dependent: :destroy
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :reviews, dependent: :destroy

  accepts_nested_attributes_for :category

  validates :title, presence: true
  validates :description, presence: true
  validates :category, presence: true


end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  validates :msg, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_categories

  helper_method :can_edit

  private
    def can_edit
      if current_user
        current_user.is_admin
      else
        false
      end
    end
    def set_categories
      @categories = Category.all
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  before_action :can_manage

  respond_to :html

  def index
  end

  def show
    respond_with(@category)
  end

  def new
    @category = Category.new
    respond_with(@category)
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    @category.save
    respond_with(@category)
  end

  def update
    @category.update(category_params)
    respond_with(@category)
  end

  def destroy
    @category.destroy
    respond_with(@category)
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
    def can_manage
      unless current_user and current_user.is_admin
        redirect_to products_path, notice: 'Only Admin allow to manage'
      end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :can_manage, except: [:index, :show]

  before_action :authenticate_user!, except: [:index,:show]

  respond_to :html

  def index
    if params[:category_id]
      @products = Category.find(params[:category_id]).products
    else
      @products = Product.includes(:category).all
    end

    respond_with(@products)
  end

  def show
    respond_with(@product)
  end

  def new

    @product = Product.new
    @product.build_category

    respond_with(@product)
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
      else
        format.html { render 'new'}
      end
    end

  end

  def update
    @product.update(product_params)
    respond_with(@product)
  end

  def destroy
    @product.destroy
    respond_with(@product)
  end

  private
    def set_product
      @product = Product.includes(:reviews).find(params[:id])
    end

    def product_params
      params.require(:product).permit(:title, :description, :category_id, category_attributes: [ :id ])
    end

    def can_manage
      unless current_user and current_user.is_admin
        redirect_to products_path, notice: 'Only Admin allow to manage'
      end
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  before_action :can_manage, except: [:index, :show, :create]

  before_action :authenticate_user!

  respond_to :html, :js

  def index
    @reviews = Review.all
    respond_with(@reviews)
  end

  def show
    respond_with(@review)
  end

  def edit
  end

  def create
    @review = current_user.reviews.new(review_params)
    @review.save
    @product = @review.product
    respond_with(@review)
  end

  def update
    @review.update(review_params)
    respond_with(@review.product,@review)
  end

  def destroy
    @review.destroy
    head :ok
  end

  private
    def set_review
      @review = Review.find(params[:id])
    end

    def review_params
      params.require(:review).permit(:msg, :user_id, :product_id)
    end
    def can_manage
      unless current_user and current_user.is_admin
        redirect_to :back, notice: 'Only Admin allow to manage'
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/categories/_form.html.erb
<div class="col-md-6">
    <%= form_for @category, html: {class: 'form-horizontal'}  do |f| %>
      <% if @category.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
          <ul>
          <% @category.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :name, class: 'col-lg-2 control-label'  %>
        <div class="col-lg-10">
            <%= f.text_field :name, class: 'form-control'  %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-10 col-lg-offset-2">
          <%= f.submit class: 'btn btn-success'%>
        </div>
      </div>
    <% end %>
</div>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.name, category %></td>
        <td><%= link_to 'Edit', edit_category_path(category), class: 'btn btn-xs btn-warning' %>
        <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path, class: 'btn btn-success' %>

app/views/categories/new.html.erb
<h1>New category</h1>
<div class="col-md-12">
<%= link_to 'Back', categories_path, class: 'btn btn-default pull-right' %>
</div>
<%= render 'form' %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">SHOP</a>
  </div>
  <div class="navbar-collapse collapse navbar-responsive-collapse">

    <ul class="nav navbar-nav navbar-right">
      <%- if user_signed_in?%>
        <li><a href="#">Hello, user!</a></li>
        <li><%= link_to 'Logout', destroy_user_session_path, :method=>:delete %></li>
      <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_menu.html.erb
<ul class="list-group">
  <li class="list-group-item">
    <%= link_to 'All', products_path %>
  </li>
    <%- @categories.each do |category| %>
          <li class="list-group-item">
            <%= link_to category.name.capitalize, category_products_path(category) %>
          </li>
    <% end %>
  <%- if can_edit %>
      <li class="list-group-item"><%= link_to 'Manage Categories', categories_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Products</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    '//maxcdn.bootstrapcdn.com/bootswatch/3.3.1/yeti/bootstrap.min.css' %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header'%>
<% if alert %>
    <div id="page-message" class="page-message alert">
      <%= alert %>
    </div>
<% end %>

<% if notice %>
    <div id="page-message" class="page-message notice">
      <%= notice %>
    </div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-2">
      <%= render 'layouts/menu' %>
    </div>
    <div class="col-md-10">
        <%= yield %>
    </div>
  </div>
</div>


</body>
</html>

app/views/products/_form.html.erb
<div class="col-md-6">
    <%= form_for @product, html: {class: 'form-horizontal'} do |f| %>
      <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
          <% @product.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

        <div class="form-group">
          <%= f.label :title, class: 'col-lg-2 control-label' %>
          <div class="col-lg-10">
            <%= f.text_field :title, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :description, class: 'col-lg-2 control-label' %>
          <div class="col-lg-10">
            <%= f.text_area :description, class: 'form-control',rows: '10', cols: '45' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :category, class: 'col-lg-2 control-label' %>
          <div class="col-lg-10">
            <%= f.collection_select :category_id, @categories, :id, :name, { prompt: false }, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-lg-10 col-lg-offset-2">
            <%= link_to 'Back', products_path, class: 'btn btn-warning' %>
            <%= f.submit class: 'btn btn-success' %>
          </div>
        </div>
    <% end %>
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>
<div class="col-md-12">
    <%= link_to 'Show Product', @product, class: 'btn btn-default pull-right' %>
  <br>
  <br>
</div>
<%= render 'form' %>

app/views/products/index.html.erb
<%- if can_edit %>
    <%= link_to 'New Product', new_product_path, class: 'btn btn-success' %>
    <br>
    <br>
<% end %>
<% @products.each do |product| %>
    <div class="col-md-12">
        <%= link_to  product.title,product %>
        <br>
        <%- if can_edit %>
           <%= link_to 'Edit', edit_product_path(product), class: 'btn btn-xs btn-warning' %>
           <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %>
           <%= link_to 'Manage Reviews', product_reviews_path(product),class: 'btn btn-xs btn-default' %>
          <br>
        <% end %>
        <br>
    </div>
<% end %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<div class="row">
  <div class="col-md-6" id="empty_img">
  </div>
  <div class="col-md-6">
    <h3><%= @product.title %>
      <%- if can_edit %>
          <%= link_to 'Edit', edit_product_path(@product), class: 'btn btn-default pull-right' %>
      <% end %>
    </h3>
    <br>
    <p><%= @product.description %></p>
  </div>
</div>

<%- if user_signed_in? %>
    <div class="row">
      <div class="col-md-12">
        <hr>
        <h3>Leave your feedback for this product</h3>
        <%= form_for [@product, Review.new], :html => {:class => 'form-horizontal'}, remote: true do |f|   %>
            <%=f.hidden_field :product_id, value: @product.id%>
            <div class="form-group">
              <div class="col-lg-12">
                <%= f.text_area :msg, :placeholder => 'Write your review here', class: 'form-control' %>
              </div>
            </div>
            <div class="form-group">
                <div class="col-lg-2">
                  <%= f.submit 'Add review', class: 'btn btn-success', :disable_with => 'Please wait..' %>
                </div>
            </div>
        <% end %>
      </div>
    </div>
<% end %>

<div class="row">
  <h3>Feedbacks</h3>
  <div class="col-md-12" id="review_append">
      <%- @product.reviews.order('created_at DESC').each do |review| %>
          <%= render partial: 'reviews/review', :locals => {:review => review, :product => @product} %>
      <% end %>
    </div>
</div>

app/views/reviews/_form.html.erb
<%= form_for [@review.product,@review], html: {class: 'form-horizontal'}  do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="form-group">
      <%= f.label :msg, class: 'col-lg-2 control-label'  %>
      <div class="col-lg-10">
        <%= f.text_area :msg, class: 'form-control'  %>
      </div>
    </div>
    <div class="form-group">
        <%= f.submit class: 'btn btn-success' %>
    </div>
<% end %>

app/views/reviews/_review.html.erb
<div class="review_item">
    <div class="col-md-12"><%= review.msg %><br></div>
    <div class="col-md-12"><%= review.user.email %>
      <%- if can_edit %>
      <div class="pull-right">
        <%= link_to 'Edit', edit_product_review_path(@product, review), class:'text-warning' %>
        <%= link_to 'Remove', product_review_path(@product, review), method: :delete, class:'text-danger remove_review', remote: true %>
      </div>
      <% end %>
      <br>
      <br>
    </div>
</div>

app/views/reviews/create.js.erb
$('#review_append').prepend("<%= escape_javascript(render partial: 'reviews/review', :locals => {:review => @review })%>");

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Back to Product', product_path(@review.product) %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table class="table">
  <thead>
    <tr>
      <th>Msg</th>
      <th>Product</th>
      <th>User</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr class="review_item">
        <td><%= review.msg %></td>
        <td><%= review.product.title %></td>
        <td><%= review.user.email %></td>
        <td>
        <%= link_to 'Show', product_review_path(review.product, review)%>
        <%= link_to 'Edit', edit_product_review_path(review.product, review) %>
        <%= link_to 'Destroy', product_review_path(review.product, review), method: :delete, data: { confirm: 'Are you sure?' }, class: 'remove_review_index', remote: true %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reviews/show.html.erb
<p>
  <strong>Msg:</strong>
  <%= @review.msg %>
</p>

<p>
  <strong>Product:</strong>
  <%= @review.product.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @review.user.email %>
</p>

<%= link_to 'Edit', edit_product_review_path(@review.product,@review) %> |
<%= link_to 'To Product', product_path(@review.product) %>